app:
    resource: "@AppBundle/Controller/"
    type:     annotation

logout:
    path: /logout

login:
    path: /login
    defaults:  { _controller: AppBundle:Security:login }

login_check:
    path: /login_check